use crate::addrgen::AddressGenerator;
use crate::DAY_IN_LEDGERS;
use arbitrary::Unstructured;
use soroban_sdk::testutils::arbitrary::arbitrary;
use std::vec::Vec as RustVec;

pub const NUMBER_OF_ADDRESSES: usize = 3;

/// Input generated by the fuzzer as the argument to `fuzz_target!`.
///
/// It consists of addresses and a series of commands that operate on them.
#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub struct Input {
    pub address_generator: AddressGenerator,
    pub transactions: RustVec<Transaction>,
}

#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub struct Transaction {
    pub commands: RustVec<Command>,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(1..=DAY_IN_LEDGERS))]
    pub advance_ledgers: u32,
}

#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub enum Command {
    Mint(MintInput),
    Approve(ApproveInput),
    TransferFrom(TransferFromInput),
    Transfer(TransferInput),
    BurnFrom(BurnFromInput),
    Burn(BurnInput),
}

#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub struct MintInput {
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(i128::MIN..=i128::MAX))]
    pub amount: i128,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub to_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| {
        // biased bool - only sometimes decline the auth
        Ok(<[bool; NUMBER_OF_ADDRESSES]>::try_from(
            std::iter::from_fn(|| Some(u.ratio(9, 10).unwrap_or(true)))
                .take(NUMBER_OF_ADDRESSES)
                .collect::<Vec<_>>()
        ).unwrap())
    })]
    pub auths: [bool; NUMBER_OF_ADDRESSES],
}

#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub struct ApproveInput {
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(i128::MIN..=i128::MAX))]
    pub amount: i128,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=DAY_IN_LEDGERS * 30))]
    pub expiration_ledger: u32,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub from_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub spender_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| {
        // biased bool - only sometimes decline the auth
        Ok(<[bool; NUMBER_OF_ADDRESSES]>::try_from(
            std::iter::from_fn(|| Some(u.ratio(9, 10).unwrap_or(true)))
                .take(NUMBER_OF_ADDRESSES)
                .collect::<Vec<_>>()
        ).unwrap())
    })]
    pub auths: [bool; NUMBER_OF_ADDRESSES],
}

#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub struct TransferFromInput {
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(i128::MIN..=i128::MAX))]
    pub amount: i128,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub spender_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub from_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub to_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| {
        // biased bool - only sometimes decline the auth
        Ok(<[bool; NUMBER_OF_ADDRESSES]>::try_from(
            std::iter::from_fn(|| Some(u.ratio(9, 10).unwrap_or(true)))
                .take(NUMBER_OF_ADDRESSES)
                .collect::<Vec<_>>()
        ).unwrap())
    })]
    pub auths: [bool; NUMBER_OF_ADDRESSES],
}

#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub struct TransferInput {
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(i128::MIN..=i128::MAX))]
    pub amount: i128,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub from_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub to_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| {
        // biased bool - only sometimes decline the auth
        Ok(<[bool; NUMBER_OF_ADDRESSES]>::try_from(
            std::iter::from_fn(|| Some(u.ratio(9, 10).unwrap_or(true)))
                .take(NUMBER_OF_ADDRESSES)
                .collect::<Vec<_>>()
        ).unwrap())
    })]
    pub auths: [bool; NUMBER_OF_ADDRESSES],
}

#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub struct BurnFromInput {
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(i128::MIN..=i128::MAX))]
    pub amount: i128,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub spender_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub from_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| {
        // biased bool - only sometimes decline the auth
        Ok(<[bool; NUMBER_OF_ADDRESSES]>::try_from(
            std::iter::from_fn(|| Some(u.ratio(9, 10).unwrap_or(true)))
                .take(NUMBER_OF_ADDRESSES)
                .collect::<Vec<_>>()
        ).unwrap())
    })]
    pub auths: [bool; NUMBER_OF_ADDRESSES],
}

#[derive(Clone, Debug, arbitrary::Arbitrary)]
pub struct BurnInput {
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(i128::MIN..=i128::MAX))]
    pub amount: i128,
    #[arbitrary(with = |u: &mut Unstructured| u.int_in_range(0..=NUMBER_OF_ADDRESSES - 1))]
    pub from_account_index: usize,
    #[arbitrary(with = |u: &mut Unstructured| {
        // biased bool - only sometimes decline the auth
        Ok(<[bool; NUMBER_OF_ADDRESSES]>::try_from(
            std::iter::from_fn(|| Some(u.ratio(9, 10).unwrap_or(true)))
                .take(NUMBER_OF_ADDRESSES)
                .collect::<Vec<_>>()
        ).unwrap())
    })]
    pub auths: [bool; NUMBER_OF_ADDRESSES],
}
